//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_Country()
        {
            this.Mst_State = new HashSet<Mst_State>();
        }
    
        public int Cn_Id { get; set; }
        public string Cn_Name { get; set; }
        public Nullable<System.DateTime> Cn_RecordCreated { get; set; }
        public Nullable<System.DateTime> Cn_RecordUpdated { get; set; }
        public Nullable<int> Cn_RecordCreatedBy { get; set; }
        public Nullable<int> Cn_RecordUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mst_State> Mst_State { get; set; }
    }
}
