//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Reason
    {
        public int Re_No { get; set; }
        public string Re_Desc { get; set; }
        public Nullable<short> Re_Status { get; set; }
        public Nullable<System.DateTime> Re_RecordCreated { get; set; }
        public Nullable<System.DateTime> Re_RecordUpdated { get; set; }
        public Nullable<int> Re_RecordCreatedBy { get; set; }
        public Nullable<int> Re_RecordUpdatedBy { get; set; }
    }
}
