//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Charge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_Charge()
        {
            this.Mst_ChargeDetails = new HashSet<Mst_ChargeDetails>();
        }
    
        public int Chg_Id { get; set; }
        public string Chg_Name { get; set; }
        public System.DateTime Chg_ReferenceDate { get; set; }
        public short Chg_Status { get; set; }
        public Nullable<System.DateTime> Chg_RecordCreated { get; set; }
        public Nullable<System.DateTime> Chg_RecordUpdated { get; set; }
        public Nullable<int> Chg_RecordCreatedBy { get; set; }
        public Nullable<int> Chg_RecordUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mst_ChargeDetails> Mst_ChargeDetails { get; set; }
    }
}
