//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_City()
        {
            this.Mst_PinCode = new HashSet<Mst_PinCode>();
        }
    
        public int Ct_Id { get; set; }
        public string Ct_Desc { get; set; }
        public Nullable<int> Ct_StateId { get; set; }
        public Nullable<System.DateTime> Ct_RecordCreated { get; set; }
        public Nullable<System.DateTime> Ct_RecordUpdated { get; set; }
        public Nullable<int> Ct_RecordCreatedBy { get; set; }
        public Nullable<int> Ct_RecordUpdatedBy { get; set; }
    
        public virtual Mst_State Mst_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mst_PinCode> Mst_PinCode { get; set; }
    }
}
