//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_ProductRate
    {
        public int Pr_Id { get; set; }
        public System.DateTime Pr_Date { get; set; }
        public short Pr_Product { get; set; }
        public int Pr_Purity { get; set; }
        public decimal Pr_GrossRate { get; set; }
        public short Pr_Deductions { get; set; }
        public decimal Pr_DeductionsAmount { get; set; }
        public decimal Pr_NetRate { get; set; }
        public Nullable<System.DateTime> Pr_RecordCreated { get; set; }
        public Nullable<System.DateTime> Pr_RecordUpdated { get; set; }
        public Nullable<int> Pr_RecordCreatedBy { get; set; }
        public Nullable<int> Pr_RecordUpdatedBy { get; set; }
    }
}
