//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_DocumentMaster
    {
        public int Doc_Id { get; set; }
        public string Doc_DocumentName { get; set; }
        public Nullable<short> Doc_DocumentType { get; set; }
        public Nullable<bool> Doc_ExpiryDateApplicable { get; set; }
        public Nullable<short> Doc_Status { get; set; }
        public Nullable<System.DateTime> Doc_RecordCreated { get; set; }
        public Nullable<System.DateTime> Doc_RecordUpdated { get; set; }
        public Nullable<int> Doc_RecordCreatedBy { get; set; }
        public Nullable<int> Doc_RecordUpdatedBy { get; set; }
    }
}
