//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_ProductRateDetails
    {
        public int Prd_Id { get; set; }
        public int Prd_FkId { get; set; }
        public int Prd_Purity { get; set; }
        public decimal Prd_GrossRate { get; set; }
        public short Prd_Deductions { get; set; }
        public decimal Prd_DeductionsAmount { get; set; }
        public decimal Prd_NetRate { get; set; }
        public Nullable<System.DateTime> Prd_RecordCreated { get; set; }
        public Nullable<System.DateTime> Prd_RecordUpdated { get; set; }
        public Nullable<int> Prd_RecordCreatedBy { get; set; }
        public Nullable<int> Prd_RecordUpdatedBy { get; set; }
    
        public virtual Mst_ProductRate Mst_ProductRate { get; set; }
    }
}
