//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_State
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_State()
        {
            this.Mst_City = new HashSet<Mst_City>();
        }
    
        public int St_Id { get; set; }
        public string St_Code { get; set; }
        public string St_Desc { get; set; }
        public Nullable<int> St_CountryId { get; set; }
        public Nullable<System.DateTime> St_RecordCreated { get; set; }
        public Nullable<System.DateTime> St_RecordUpdated { get; set; }
        public Nullable<int> St_RecordCreatedBy { get; set; }
        public Nullable<int> St_RecordUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mst_City> Mst_City { get; set; }
        public virtual Mst_Country Mst_Country { get; set; }
    }
}
