//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_PinCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_PinCode()
        {
            this.Mst_Branch = new HashSet<Mst_Branch>();
        }
    
        public int Pc_Id { get; set; }
        public string Pc_Desc { get; set; }
        public string Pc_AreaName { get; set; }
        public int Pc_CityId { get; set; }
        public int Pc_ZoneId { get; set; }
        public Nullable<System.DateTime> Pc_RecordCreated { get; set; }
        public Nullable<System.DateTime> Pc_RecordUpdated { get; set; }
        public Nullable<int> Pc_RecordCreatedBy { get; set; }
        public Nullable<int> Pc_RecordUpdatedBy { get; set; }
    
        public virtual Mst_City Mst_City { get; set; }
        public virtual Mst_Zone Mst_Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mst_Branch> Mst_Branch { get; set; }
    }
}
