//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_SourceofApplication
    {
        public int Soa_Id { get; set; }
        public string Soa_Name { get; set; }
        public Nullable<short> Soa_Category { get; set; }
        public Nullable<short> Soa_Status { get; set; }
        public Nullable<System.DateTime> Soa_RecordCreated { get; set; }
        public Nullable<System.DateTime> Soa_RecordUpdated { get; set; }
        public Nullable<int> Soa_RecordCreatedBy { get; set; }
        public Nullable<int> Soa_RecordUpdatedBy { get; set; }
    }
}
