//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_ChildDeviation
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public Nullable<decimal> ApproveDistanceLimit { get; set; }
        public Nullable<decimal> MinRange { get; set; }
        public Nullable<decimal> MaxRange { get; set; }
        public Nullable<int> UserCategoryId { get; set; }
        public Nullable<decimal> ThreasoldLimit { get; set; }
        public Nullable<System.DateTime> RecordCreated { get; set; }
        public Nullable<System.DateTime> RecordUpdated { get; set; }
        public Nullable<int> RecordCreatedBy { get; set; }
        public Nullable<int> RecordUpdatedBy { get; set; }
    
        public virtual Mst_ParentDeviation Mst_ParentDeviation { get; set; }
    }
}
