//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Zone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mst_Zone()
        {
            this.Mst_PinCode = new HashSet<Mst_PinCode>();
        }
    
        public int Zne_No { get; set; }
        public string Zne_Desc { get; set; }
        public Nullable<System.DateTime> Zne_RecordCreated { get; set; }
        public Nullable<System.DateTime> Zne_RecordUpdated { get; set; }
        public Nullable<int> Zne_RecordCreatedBy { get; set; }
        public Nullable<int> Zne_RecordUpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mst_PinCode> Mst_PinCode { get; set; }
    }
}
