//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_PenaltySlab
    {
        public int Ps_Id { get; set; }
        public System.DateTime Ps_Datewef { get; set; }
        public decimal Ps_Penalty { get; set; }
        public int Ps_Accounthead { get; set; }
        public Nullable<System.DateTime> Ps_RecordCreated { get; set; }
        public Nullable<System.DateTime> Ps_RecordUpdated { get; set; }
        public Nullable<int> Ps_RecordCreatedBy { get; set; }
        public Nullable<int> Ps_RecordUpdatedBy { get; set; }
    }
}
