//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Ornament
    {
        public int Orn_Id { get; set; }
        public string Orn_Name { get; set; }
        public Nullable<short> Orn_Product { get; set; }
        public Nullable<short> Orn_Status { get; set; }
        public Nullable<System.DateTime> Orn_RecordCreated { get; set; }
        public Nullable<System.DateTime> Orn_RecordUpdated { get; set; }
        public Nullable<int> Orn_RecordCreatedBy { get; set; }
        public Nullable<int> Orn_RecordUpdatedBy { get; set; }
    }
}
