//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_SchemeMaster
    {
        public int SchemeId { get; set; }
        public short Product { get; set; }
        public string SchemeName { get; set; }
        public short SchemeType { get; set; }
        public short Frequency { get; set; }
        public Nullable<decimal> MinTenure { get; set; }
        public Nullable<decimal> MaxTenure { get; set; }
        public Nullable<decimal> MinLoanAmount { get; set; }
        public Nullable<decimal> MaxLoanAmount { get; set; }
        public Nullable<decimal> MinLTVPerc { get; set; }
        public Nullable<decimal> MaxLTVPerc { get; set; }
        public Nullable<decimal> MinRoiPerc { get; set; }
        public Nullable<decimal> MaxRoiPerc { get; set; }
        public Nullable<int> GracePeriod { get; set; }
        public Nullable<decimal> EffectiveRoiPerc { get; set; }
        public Nullable<int> LockInPeriod { get; set; }
        public Nullable<short> ProcessingFeeType { get; set; }
        public Nullable<decimal> ProcessingCharges { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<System.DateTime> RecordCreated { get; set; }
        public Nullable<System.DateTime> RecordUpdated { get; set; }
        public Nullable<int> RecordCreatedBy { get; set; }
        public Nullable<int> RecordUpdatedBy { get; set; }
    }
}
