//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblaccountmaster
    {
        public int AccountID { get; set; }
        public string Name { get; set; }
        public string Alies { get; set; }
        public int GPID { get; set; }
        public double OpeningBalance { get; set; }
        public string DrCr { get; set; }
        public string PanNo { get; set; }
        public double InterestRate { get; set; }
        public string InterestMethod { get; set; }
        public string GroupCompany { get; set; }
        public string Address { get; set; }
        public string BankAcNo { get; set; }
        public double MICRNo { get; set; }
        public string AccountType { get; set; }
        public string IFSNo { get; set; }
        public int AreaID { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Suspended { get; set; }
        public string GSTIN { get; set; }
    }
}
