//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfinancialyear
    {
        public int FinancialyearID { get; set; }
        public System.DateTime Financialyearfrom { get; set; }
        public System.DateTime Financialyearto { get; set; }
        public string Financialyear { get; set; }
        public int CompID { get; set; }
    }
}
