//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangalWebProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupMaster
    {
        public int GPID { get; set; }
        public string GPName { get; set; }
        public string GPType { get; set; }
        public int PID { get; set; }
        public int SID { get; set; }
        public string PrintSchedule { get; set; }
        public string ScheduleNo { get; set; }
        public string Remark { get; set; }
    }
}
